### PR TITLE
Fix conflicting resource conditions in 1.20.1

### LINKED ISSUE #129: Issue with multiloader recipe conditions
### Describe the bug

if a forge mod that has both fabric and forge conditions in a recipe is used with FFAPI, the recipe will be skipped.

### Steps to reproduce

1. install a forge mod with conditions for multiple loaders ([simple radio](https://www.curseforge.com/minecraft/mc-mods/simple-voice-radio), in this case)
2. install FFAPI
3. recipes will be skipped on startup

### Logs

https://gist.github.com/CodinGlitch/ef918c07f87fae43feccde829463defe

### Additional context

i am the developer for [Simple Voice Radio](https://www.curseforge.com/minecraft/mc-mods/simple-voice-radio), and was receiving a few reports that recipes weren't loading, so after taking a look it seems like when having both recipe conditions for fabric and forge, the fabric api tries to load the fabric recipe conditions, which aren't registered due to the mod being forge-based.

i realize that changes to the api itself should be kept to a minimum, so there may not be a proper solution that can be made on this end, but i figured i should reach out anyway in case there is any potential action i can take to avoid this issue going forward (a solution would be to do data generation per-loader, though it's not a pretty one)

one of the recipes from my mod contains the following which would cause this issue:
```json
{
  "fabric:load_conditions": [
    {
      "condition": "simpleradio:items_enabled",
      "values": [
        "transceiver"
      ]
    }
  ],
  "forge:condition": {
    "type": "simpleradio:items_enabled",
    "item": "transceiver"
  },
  "neoforge:conditions": [
    {
      "type": "simpleradio:items_enabled",
      "item": "transceiver"
    }
  ],
}
```

### LINKED ISSUE #154: Incompatibility with Fluid Tanks (NeoForge 21.1.50, Fluid Tanks: 21.1.0, Forgified Fabric: 0.102.0)
For some reason I'm able to create fluid tanks without Forgified Fabric, but with this mod installed it seems to delete the recipe and cause me to be unable to create a fluid tank. Not sure how this happens though... either way I have opened the issue with Fluid Tanks Github page: https://github.com/Kotori316/FluidTank2/issues/439

[Log file](https://github.com/user-attachments/files/16992397/latest.log)

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
Fixes #154
Fixes #129
This is somewhat akin to 59440bcc3f445bcbeb3181d7fd156f43ae11582c, but for 1.20.1

I got a bug report over at https://github.com/ThexXTURBOXx/Balkons-WeaponMod-Legacy/issues/97 regarding this

### CODE REVIEW

File: fabric-resource-conditions-api-v1/src/main/java/net/fabricmc/fabric/api/resource/conditions/v1/ResourceConditions.java [hunk 1]
```diff
@@ -122,6 +122,7 @@ public static Predicate<JsonObject> get(Identifier identifier) {
 	 * <p>If an exception is thrown during condition testing, it will be caught and logged, and false will be returned.
 	 */
 	public static boolean objectMatchesConditions(JsonObject object) {
+		if (JsonHelper.hasArray(object, "conditions")) return true;
```
Comment (ThexXTURBOXx) [inline fabric-resource-conditions-api-v1/src/main/java/net/fabricmc/fabric/api/resource/conditions/v1/ResourceConditions.java:125]: I am not 100% sure whether there is a better way to reference `"conditions"`. I couldn't find a constant which contains this string in Forge's source code, so I hardcoded it here for now... Is there something?

**Review by Su5eD — APPROVED** [review]
